# Generated by Django 4.1 on 2022-11-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cpf',
            field=models.CharField(max_length=255, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_1',
            field=models.CharField(max_length=255, null=True, verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_2',
            field=models.CharField(max_length=255, null=True, verbose_name='Contato 2'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rg',
            field=models.CharField(max_length=255, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Full name'),
        ),
    ]
