# Generated by Django 4.1 on 2023-01-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(max_length=255, null=True, verbose_name='Profissão'),
        ),
    ]
