# Generated by Django 4.1 on 2022-12-05 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0008_alter_profile_full_name'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='comments',
            field=models.TextField(max_length=1000, null=True, verbose_name='Comentários'),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_at',
            field=models.DateField(auto_created=True, null=True, verbose_name='Data de criação'),
        ),
        migrations.AddField(
            model_name='contract',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Titular do contrato'),
        ),
        migrations.AddField(
            model_name='contract',
            name='reference_year',
            field=models.IntegerField(null=True, verbose_name='Ano de referência'),
        ),
        migrations.AddField(
            model_name='contract',
            name='registration_fee',
            field=models.FloatField(null=True, verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='contract',
            name='registration_fee_status',
            field=models.BooleanField(null=True, verbose_name='Status Matrícula'),
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.BooleanField(null=True, verbose_name='Status do contrato'),
        ),
        migrations.AddField(
            model_name='contract',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.profile', verbose_name='Aluno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='tuition_apr',
            field=models.BooleanField(default=True, verbose_name='Abril'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='tuition_aug',
            field=models.BooleanField(default=True, verbose_name='Agosto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='tuition_dec',
            field=models.BooleanField(default=True, verbose_name='Dezembro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='tuition_feb',
            field=models.BooleanField(default=True, verbose_name='Fevereiro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='tuition_jan',
            field=models.BooleanField(default=True, verbose_name='Janeiro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='tuition_jul',
            field=models.BooleanField(default=True, verbose_name='Julho'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='tuition_jun',
            field=models.BooleanField(default=True, verbose_name='Junho'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='tuition_mar',
            field=models.BooleanField(default=True, verbose_name='Março'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='tuition_may',
            field=models.BooleanField(default=True, verbose_name='Maio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='tuition_nov',
            field=models.BooleanField(default=True, verbose_name='Novembro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='tuition_oct',
            field=models.BooleanField(default=True, verbose_name='Outubro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='tuition_set',
            field=models.BooleanField(default=True, verbose_name='Setembro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='value',
            field=models.FloatField(null=True, verbose_name='Valor'),
        ),
    ]
