# Generated by Django 4.1 on 2022-12-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profile_full_name'),
        ('billing', '0002_contract_comments_contract_created_at_contract_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Curso')),
                ('description', models.TextField(max_length=1000, verbose_name='Descrição do Curso')),
                ('teachers', models.ManyToManyField(to='profiles.profile', verbose_name='Professor')),
            ],
        ),
    ]
