# Generated by Django 4.1 on 2022-12-05 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='billing.course', verbose_name='Curso'),
        ),
    ]
