# Generated by Django 4.1 on 2023-01-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_course_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='tuition_value',
            field=models.FloatField(null=True, verbose_name='Mensalidade'),
        ),
    ]
