# Generated by Django 4.1 on 2022-11-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_author',
            field=models.CharField(default='default_author', max_length=255, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(null=True, upload_to='blog/posts/%d/%m/%Y', verbose_name='Img'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_text',
            field=models.TextField(default='default_text', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(default='default_title', max_length=255, verbose_name='Title'),
        ),
    ]
